os: WMF 5

install:
  - ps: Install-PackageProvider -Name nuget -MinimumVersion 2.8.5.201 -force
  - ps: Install-Module pester -Scope CurrentUser -Force
 
build: false

test_script:
  - ps: . .\Tests\appveyor.pester.ps1 -Test -Finalize
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))